### ISSUE TITLE
CONSOLE GIVE 

### ISSUE THREAD

**Issue by Mr-Rene** [GamerMedic/UndeadPandemic#8]
Hi, I'm trying to enter the command in the console, undeadpandemic give Rene_Angel firstaid adrenaline 1 but it doesn't do anything and doesn't output anything in the console either.

**Comment by GamerMedic** [comment]
Can you please try another item and see if that works?

I need to know if this is a command problem or just a problem with adrenaline.

Thanks

**Comment by Mr-Rene** [comment]
Hello, 
The other items seem to work, the only problem is the Paracetamol item, it gives me some item with a weapon that is not even functional.

**Comment by Mr-Rene** [comment]
As for the Paracetamol, the other items work without problems, only the Paracetamol doesn't work it gives me item of some weapon that doesn't work.

**Comment by Mr-Rene** [comment]
Greetings and apologies for my poor orientation, I didn't know what was being addressed first. So if I enter a command that is supposed to give me an item e.g. Antibiotics, it doesn't seem to do anything and doesn't seem to register.

**Comment by GamerMedic** [comment]
Okay, no problem. I'll have a look into it and get back to you as soon as possible

**Comment by Mr-Rene** [comment]
Okay, nice

**Comment by GamerMedic** [comment]
Hi @Mr-Rene,

I've tested this issue and can't replicate it. If you're still having trouble, please let me know.
